### ISSUE TITLE
I think It's a Virus

### ISSUE THREAD

**Issue by davidspy** [khalequzzaman17/gateway_fees#1]
Hi,

I've installed the Addon on my Server, but when I try to enter the configaddonmods.php Page, I get this error: md5 Code manipulation detected

**Comment by khalequzzaman17** [comment]
Hi there! You should contact your hosting provider regarding this. Or, you may feel free to ask me to check and solve the issue in skype, live:khalequzzaman17.

**Comment by davidspy** [comment]
Hi,

I downt have Skype installed.
What PHP Version schould I use?
And waht IONCube version is requrierd?

Best Regards

2019-09-28 20:07 GMT+02:00, khalequzzaman17 <notifications@github.com>:

**Comment by davidspy** [comment]
Hello?

**Comment by khalequzzaman17** [comment]
Try with PHP version 7.3 latest version of ioncube

**Comment by davidspy** [comment]
I've done this, but i didnt work, cloud you send me an unencrypted version?

**Comment by davidspy** [comment]
You are not using ioncube

**Comment by davidspy** [comment]
You use md5

**Comment by khalequzzaman17** [comment]
Sorry, I can't share the unencrypted version. If you have still any problem, you may create a skype account and feel free to ask me to check and solve the issue in skype, live:khalequzzaman17

**Comment by davidspy** [comment]
Cloud you explain my, how i can fix the error:
md5 Code manipulation detected

what php extention do i need?
I use Version PHP 7.3.9

**Comment by khalequzzaman17** [comment]
As I have told before please contact with me in skype.
