### ISSUE TITLE
md5 Code manipulation detected

### ISSUE THREAD

**Issue by grand-lotus-iroh** [khalequzzaman17/gateway_fees#2]
tried to upload and check this out, doesn't work.

can you please remove encryption? i want to study / learn from the hook specifically....

**Comment by khalequzzaman17** [comment]
Sorry for the delay reply.

Sorry, I can't share decrypted files. If you need any kind help, you can contact me at skype live:khalequzzaman17

**Comment by marens101** [comment]
I'm getting the same issue, ~~and skype says you don't exist.~~ Fixed, messaged you on Skype
